### ISSUE TITLE
Does DASH support fully encrypted segments?

### ISSUE THREAD

**Issue by AquilesCanta** [Dash-Industry-Forum/Guidelines-Security#16]
Quick question: Does DASH support fully encrypted segments? If yes, any vague idea of how widely it's supported by players? 

I mean chunks/segments of which every byte is encrypted, similar to what HLS's `#EXT-X-KEY:METHOD=AES-128,...` describes.

**Comment by lpiron** [comment]
There is the specification 23009-4 describing how to fully encrypt a segment. This is similar to the AES-128 encryption mode in HLS.
To my knowledge, there is no support for this, either in the DASH player for the extra signaling that is needed nor in the video player that do not support decryption before demux.

**Comment by AquilesCanta** [comment]
Got it. Thank you very much.
