### ISSUE TITLE
Should recommended client workflows enable an error response to be provided both to the client and the DRM system?

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/Guidelines-Security#5]
Copy-pasting comment from @ojw28 

> More generally, the failure model described in this document appears to mean that a license server cannot both signal failure in a response, and provide a response to be passed to the DRM system for processing. In contrast to this, I've seen systems where a license server wants to indicate failure to the application and also pass a response to the DRM system. As an example, consider a system where each issued license is valid for 5 minutes, and is refreshed every 1 minute. If the user loses rights to access the content, the client will discover this when the underlying DRM system has a license that will allow successful decryption for a further 4 minutes. For this case, I've seen a setup where the response will include both an application parsable error and an opaque response to pass into the underlying DRM system. The opaque response causes the underlying DRM system to actually invalidate the license and hence prevent further decryption. Obviously this isn't particularly secure (there's an easy application-side attack where you simply prevent the response from being passed down conditional on the application parsable bit of the response indicating failure), but I think it might be seen as "better than nothing".
>
> Is this kind of system deliberately out of scope for this document? If not, I think it would be necessary to allow a failure response to still include an opaque blob to pass to the underlying DRM system (which probably isn't too hard to add in as an additional field).

**Comment by sandersaares** [comment]
My personal feeling is that this is not a very mainstream use case, so we would be better off ignoring it for now to reduce workflow complexity.

**Comment by lpiron** [comment]
Close with no action following discussion during CPS call on May 13
