### ISSUE TITLE
Remove sentence on conformance to this specification

### ISSUE THREAD

**Issue by lpiron** [Dash-Industry-Forum/Guidelines-Security#8]
This sentence in section 3
"All DASH presentations are assumed to be conforming to these guidelines. A service MAY explicitly signal itself as conforming by including the string https://dashif.org/guidelines/ in MPD@profiles"
should either be removed or modified as this document is only about encrypted content.

**Comment by sandersaares** [comment]
I support removing this statement entirely. The v5 umbrella document should be sufficient for any talk of profiles.

**Comment by lpiron** [comment]
Agreed. Will be removed

**Comment by lpiron** [comment]
PR merged, closing
